"""
Django settings for backoffice_project project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from import_export.formats.base_formats import CSV, XLSX, JSON, YAML, HTML
import os
import logging
import datetime




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k9u0hc(gp)m5pc=qgu%ed8pqqe^wx(tfahf(_$fgot_5-y_loc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

#AUTH_USER_MODEL = 'backoffice.CustomUser'


INSTALLED_APPS = [
    #my_app
    'backoffice',
    #third_party_app
    #"admin_persian",
    #'explorer',
    #'adminactions',
    #'reporting',
    "admin_interface",
    "colorfield",
    'import_export',
    'jalali_date',
    'django_extensions',
    'django_select2',
    #default_app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]

# AUTHENTICATION_BACKENDS = [
#     'backoffice.auth_backends.ProfileBackend',  # Custom backend
#     'django.contrib.auth.backends.ModelBackend',  # Default backend
# ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'backoffice.middleware.LMiddleware',
    #'backoffice.middleware.ProfileToUserMiddleware',
]

ROOT_URLCONF = 'backoffice_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backoffice_project.wsgi.application'
AUTH_USER_MODEL = 'backoffice.User'


# SESSION_ENGINE = 'django.contrib.sessions.backends.db' # Store sessions in DB
# SESSION_DB_ALIAS = 'default'
# SESSION_COOKIE_AGE = 3600 # Session expiration time in seconds

# LOGIN_URL = 'costum_login'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
 #   'default': {
 #       'ENGINE': 'django.db.backends.sqlite3',
  #      'NAME': BASE_DIR / 'db.sqlite3',
  #  }
#}

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'dbdev',
        'USER': 'prkardata',
        'PASSWORD': 's5j7d~qD}PU?Hx{N$Wb+:E',
        'HOST': '10.2.10.20',  # Example for second DB host
        'PORT': '1521',
    },
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': ('(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={})(PORT={}))'
# '(CONNECT_DATA=(SERVICE_NAME={})))'.format(os.getenv('ORACLE_DB_HOST'), os.getenv('ORACLE_DB_PORT'), os.getenv('ORACLE_DB_NAME') )),
#         'USER': os.getenv('ORACLE_DB_USER'),
#         'USER': os.getenv('ORACLE_DB_USER'),
#         'PASSWORD': os.getenv('ORACLE_DB_PASSWORD'),
#         'HOST': '',
#         'PORT': '',  # Using the retrieved port value
#     }
# }

# DATABASE_ROUTERS = ['backoffice.db_router.UserBasedRouter']

# AUTHENTICATION_BACKENDS = ['backoffice.auth.CustomAuthenticationBackend', 'django.contrib.auth.backends.ModelBackend']

# EXPLORER_CONNECTIONS = {
#     'Default': 'default'
# }

# EXPLORER_DEFAULT_CONNECTION = 'default'


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'file': {
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'db_connection.log'),
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         # Logging for Django Database Connections
#         'django.db.backends': {
#             'handlers': ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
import os
import datetime

L_DATE = datetime.datetime(2025, 1, 20)
# Read expiration date from environment variable
L = os.getenv("LEX")

# Set L_DATE in settings if the environment variable is found
if L:
    try:
        L_DATE = datetime.datetime.fromisoformat(L)
    except ValueError:
        L_DATE = datetime.datetime(2025, 1, 20) 
else:
    L_DATE = datetime.datetime(2025, 1, 20) 

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         '': {  # Root logger
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / "backoffice_project" / "staticfiles",
    BASE_DIR / "static" / "js"
   ]



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

IMPORT_EXPORT_FORMATS = [XLSX, CSV]


# Add this to configure a simple in-memory cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}


# admin_interface_theme




